import '../models/app_settings.dart';

/// Translates a canonical English festival key (as returned by
/// [FestivalDetector.detect]) into the user's display language.
///
/// The English name is the single source of truth. Adding a new language
/// means adding one new map here — no other files need to change.
abstract final class FestivalNames {
  static String? localize(String? key, AppLanguage language) {
    if (key == null) return null;
    return switch (language) {
      AppLanguage.english         => key,
      AppLanguage.hindiLatin      => key,
      AppLanguage.hindiDevanagari => _deva[key] ?? key,
      AppLanguage.tamil           => _ta[key] ?? key,
      AppLanguage.bengali         => _bn[key] ?? key,
    };
  }

  static const _deva = <String, String>{
    'Baisakhi / Vishu':           'बैसाखी / विषु',
    'Makar Sankranti / Pongal':   'मकर संक्रांति / पोंगल',
    'Chaitra Navratri':           'चैत्र नवरात्रि',
    'Maha Ashtami':               'महा अष्टमी',
    'Ram Navami':                 'राम नवमी',
    'Hanuman Jayanti':            'हनुमान जयंती',
    'Holi':                       'होली',
    'Akshaya Tritiya':            'अक्षय तृतीया',
    'Buddha Purnima':             'बुद्ध पूर्णिमा',
    'Nirjala Ekadashi':           'निर्जला एकादशी',
    'Vat Savitri':                'वट सावित्री',
    'Rath Yatra':                 'रथ यात्रा',
    'Devshayani Ekadashi':        'देवशयनी एकादशी',
    'Guru Purnima':               'गुरु पूर्णिमा',
    'Nag Panchami':               'नाग पंचमी',
    'Raksha Bandhan':             'रक्षा बंधन',
    'Krishna Janmashtami':        'कृष्ण जन्माष्टमी',
    'Ganesh Chaturthi':           'गणेश चतुर्थी',
    'Anant Chaturdashi':          'अनंत चतुर्दशी',
    'Sharad Navratri':            'शारद नवरात्रि',
    'Maha Navami':                'महा नवमी',
    'Vijayadashami':              'विजयदशमी',
    'Sharad Purnima':             'शरद पूर्णिमा',
    'Dhanteras':                  'धनतेरस',
    'Naraka Chaturdashi':         'नरक चतुर्दशी',
    'Diwali':                     'दीपावली',
    'Govardhan Puja':             'गोवर्धन पूजा',
    'Bhai Dooj':                  'भाई दूज',
    'Chhath — Nahay Khay':        'छठ — नहाय खाय',
    'Chhath — Kharna':            'छठ — खरना',
    'Chhath — Sandhya Arghya':    'छठ — संध्या अर्घ्य',
    'Chhath — Usha Arghya':       'छठ — उषा अर्घ्य',
    'Devutthana Ekadashi':        'देवउठानी एकादशी',
    'Kartik Purnima':             'कार्तिक पूर्णिमा',
    'Gita Jayanti':               'गीता जयंती',
    'Vasant Panchami':            'वसंत पंचमी',
    'Maha Shivaratri':            'महाशिवरात्रि',
    'Holika Dahan':               'होलिका दहन',
    'Ekadashi':                   'एकादशी',
  };

  static const _ta = <String, String>{
    'Baisakhi / Vishu':           'வைசாகி / விஷு',
    'Makar Sankranti / Pongal':   'மகர சங்கராந்தி / பொங்கல்',
    'Chaitra Navratri':           'சைத்ர நவராத்திரி',
    'Maha Ashtami':               'மஹா அஷ்டமி',
    'Ram Navami':                 'ராம நவமி',
    'Hanuman Jayanti':            'ஹனுமான் ஜயந்தி',
    'Holi':                       'ஹோலி',
    'Akshaya Tritiya':            'அக்ஷய திரிதியை',
    'Buddha Purnima':             'புத்த பவுர்ணமி',
    'Nirjala Ekadashi':           'நிர்ஜல ஏகாதசி',
    'Vat Savitri':                'வட சாவித்திரி',
    'Rath Yatra':                 'ரத யாத்திரை',
    'Devshayani Ekadashi':        'தேவசயனி ஏகாதசி',
    'Guru Purnima':               'குரு பவுர்ணமி',
    'Nag Panchami':               'நாக பஞ்சமி',
    'Raksha Bandhan':             'ரக்ஷா பந்தன்',
    'Krishna Janmashtami':        'கிருஷ்ண ஜன்மாஷ்டமி',
    'Ganesh Chaturthi':           'விநாயக சதுர்த்தி',
    'Anant Chaturdashi':          'அனந்த சதுர்தசி',
    'Sharad Navratri':            'சரத் நவராத்திரி',
    'Maha Navami':                'மஹா நவமி',
    'Vijayadashami':              'விஜயதசமி',
    'Sharad Purnima':             'சரத் பவுர்ணமி',
    'Dhanteras':                  'தன்தேரஸ்',
    'Naraka Chaturdashi':         'நரக சதுர்தசி',
    'Diwali':                     'தீபாவளி',
    'Govardhan Puja':             'கோவர்தன் பூஜை',
    'Bhai Dooj':                  'பாய் தூஜ்',
    'Chhath — Nahay Khay':        'சட் — நஹாய் காய்',
    'Chhath — Kharna':            'சட் — கர்ணா',
    'Chhath — Sandhya Arghya':    'சட் — சாயங்கால அர்க்கியம்',
    'Chhath — Usha Arghya':       'சட் — உஷா அர்க்கியம்',
    'Devutthana Ekadashi':        'தேவுத்தான ஏகாதசி',
    'Kartik Purnima':             'கார்த்திகை பவுர்ணமி',
    'Gita Jayanti':               'கீதா ஜயந்தி',
    'Vasant Panchami':            'வசந்த பஞ்சமி',
    'Maha Shivaratri':            'மஹா சிவராத்திரி',
    'Holika Dahan':               'ஹோலிகா தகனம்',
    'Ekadashi':                   'ஏகாதசி',
  };

  static const _bn = <String, String>{
    'Baisakhi / Vishu':           'বৈশাখী / বিষু',
    'Makar Sankranti / Pongal':   'মকর সংক্রান্তি / পোঙ্গল',
    'Chaitra Navratri':           'চৈত্র নবরাত্রি',
    'Maha Ashtami':               'মহা অষ্টমী',
    'Ram Navami':                 'রাম নবমী',
    'Hanuman Jayanti':            'হনুমান জয়ন্তী',
    'Holi':                       'হোলি',
    'Akshaya Tritiya':            'অক্ষয় তৃতীয়া',
    'Buddha Purnima':             'বুদ্ধ পূর্ণিমা',
    'Nirjala Ekadashi':           'নির্জলা একাদশী',
    'Vat Savitri':                'বট সাবিত্রী',
    'Rath Yatra':                 'রথ যাত্রা',
    'Devshayani Ekadashi':        'দেবশয়নী একাদশী',
    'Guru Purnima':               'গুরু পূর্ণিমা',
    'Nag Panchami':               'নাগ পঞ্চমী',
    'Raksha Bandhan':             'রক্ষা বন্ধন',
    'Krishna Janmashtami':        'কৃষ্ণ জন্মাষ্টমী',
    'Ganesh Chaturthi':           'গণেশ চতুর্থী',
    'Anant Chaturdashi':          'অনন্ত চতুর্দশী',
    'Sharad Navratri':            'শারদ নবরাত্রি',
    'Maha Navami':                'মহা নবমী',
    'Vijayadashami':              'বিজয়দশমী',
    'Sharad Purnima':             'শরৎ পূর্ণিমা',
    'Dhanteras':                  'ধনতেরাস',
    'Naraka Chaturdashi':         'নরক চতুর্দশী',
    'Diwali':                     'দীপাবলি',
    'Govardhan Puja':             'গোবর্ধন পূজা',
    'Bhai Dooj':                  'ভাই দুজ',
    'Chhath — Nahay Khay':        'ছট — নহায় খায়',
    'Chhath — Kharna':            'ছট — খরনা',
    'Chhath — Sandhya Arghya':    'ছট — সন্ধ্যা অর্ঘ্য',
    'Chhath — Usha Arghya':       'ছট — ঊষা অর্ঘ্য',
    'Devutthana Ekadashi':        'দেবউত্থান একাদশী',
    'Kartik Purnima':             'কার্তিক পূর্ণিমা',
    'Gita Jayanti':               'গীতা জয়ন্তী',
    'Vasant Panchami':            'বসন্ত পঞ্চমী',
    'Maha Shivaratri':            'মহাশিবরাত্রি',
    'Holika Dahan':               'হোলিকা দহন',
    'Ekadashi':                   'একাদশী',
  };
}
