import '../models/app_settings.dart';

/// Translates a canonical English festival key (as returned by
/// [FestivalDetector.detect]) into the user's display language.
///
/// The English name is the single source of truth. Adding a new language
/// means adding one new map here — no other files need to change.
abstract final class FestivalNames {
  static String? localize(String? key, AppLanguage language) {
    if (key == null) return null;
    return switch (language) {
      AppLanguage.hindiDevanagari => _deva[key] ?? key,
      AppLanguage.tamil           => _ta[key] ?? key,
      AppLanguage.bengali         => _bn[key] ?? key,
      AppLanguage.odia            => _or[key] ?? key,
      AppLanguage.telugu          => _te[key] ?? key,
      AppLanguage.malayalam       => _ml[key] ?? key,
      AppLanguage.kannada         => _kn[key] ?? key,
      _                           => key,
    };
  }

  static const _deva = <String, String>{
    'Baisakhi / Vishu':                        'बैसाखी / विषु',
    'Makar Sankranti / Pongal':                'मकर संक्रांति / पोंगल',
    'Gudi Padwa / Ugadi / Chaitra Navratri':   'गुड़ी पड़वा / उगादि / चैत्र नवरात्रि',
    'Maha Ashtami':               'महा अष्टमी',
    'Ram Navami':                 'राम नवमी',
    'Hanuman Jayanti':            'हनुमान जयंती',
    'Holi':                       'होली',
    'Akshaya Tritiya':            'अक्षय तृतीया',
    'Buddha Purnima':             'बुद्ध पूर्णिमा',
    'Ganga Dussehra':             'गंगा दशहरा',
    'Nirjala Ekadashi':           'निर्जला एकादशी',
    'Vat Savitri':                'वट सावित्री',
    'Hariyali Teej':              'हरियाली तीज',
    'Hartalika Teej':             'हरतालिका तीज',
    'Rath Yatra':                 'रथ यात्रा',
    'Devshayani Ekadashi':        'देवशयनी एकादशी',
    'Guru Purnima':               'गुरु पूर्णिमा',
    'Nag Panchami':               'नाग पंचमी',
    'Raksha Bandhan':             'रक्षा बंधन',
    'Krishna Janmashtami':        'कृष्ण जन्माष्टमी',
    'Ganesh Chaturthi':           'गणेश चतुर्थी',
    'Anant Chaturdashi':          'अनंत चतुर्दशी',
    'Sharad Navratri':            'शारद नवरात्रि',
    'Golu':                       'गोलू',
    'Maha Navami':                'महा नवमी',
    'Vijayadashami':              'विजयदशमी',
    'Mahalaya Amavasya':          'महालया अमावस्या',
    'Jivitputrika Vrat (Jitiya)':          'जिवितपुत्रिका व्रत',
    'Sharad Purnima':             'शरद पूर्णिमा',
    'Karva Chauth':               'करवा चौथ',
    'Ahoi Ashtami':               'अहोई अष्टमी',
    'Dhanteras':                  'धनतेरस',
    'Naraka Chaturdashi':         'नरक चतुर्दशी',
    'Diwali':                     'दीपावली',
    'Govardhan Puja':             'गोवर्धन पूजा',
    'Bhai Dooj':                  'भाई दूज',
    'Chhath — Nahay Khay':        'छठ — नहाय खाय',
    'Chhath — Kharna':            'छठ — खरना',
    'Chhath — Sandhya Arghya':    'छठ — संध्या अर्घ्य',
    'Chhath — Usha Arghya':       'छठ — उषा अर्घ्य',
    'Devutthana Ekadashi':        'देवउठानी एकादशी',
    'Tulsi Vivah':                'तुलसी विवाह',
    'Kartik Purnima':             'कार्तिक पूर्णिमा',
    'Gita Jayanti':               'गीता जयंती',
    'Vasant Panchami':            'वसंत पंचमी',
    'Maha Shivaratri':            'महाशिवरात्रि',
    'Holika Dahan':               'होलिका दहन',
    'Ekadashi':                   'एकादशी',
  };

  static const _ta = <String, String>{
    'Baisakhi / Vishu':                        'வைசாகி / விஷு',
    'Makar Sankranti / Pongal':                'மகர சங்கராந்தி / பொங்கல்',
    'Gudi Padwa / Ugadi / Chaitra Navratri':   'குடி பட்வா / உகாதி / சைத்ர நவராத்திரி',
    'Maha Ashtami':               'மஹா அஷ்டமி',
    'Ram Navami':                 'ராம நவமி',
    'Hanuman Jayanti':            'ஹனுமான் ஜயந்தி',
    'Holi':                       'ஹோலி',
    'Akshaya Tritiya':            'அக்ஷய திரிதியை',
    'Buddha Purnima':             'புத்த பவுர்ணமி',
    'Ganga Dussehra':             'கங்கா தசஹரா',
    'Nirjala Ekadashi':           'நிர்ஜல ஏகாதசி',
    'Vat Savitri':                'வட சாவித்திரி',
    'Hariyali Teej':              'ஹரியாளி தீஜ்',
    'Hartalika Teej':             'ஹர்தாலிகா தீஜ்',
    'Rath Yatra':                 'ரத யாத்திரை',
    'Devshayani Ekadashi':        'தேவசயனி ஏகாதசி',
    'Guru Purnima':               'குரு பவுர்ணமி',
    'Nag Panchami':               'நாக பஞ்சமி',
    'Raksha Bandhan':             'ரக்ஷா பந்தன்',
    'Krishna Janmashtami':        'கிருஷ்ண ஜன்மாஷ்டமி',
    'Ganesh Chaturthi':           'விநாயக சதுர்த்தி',
    'Anant Chaturdashi':          'அனந்த சதுர்தசி',
    'Sharad Navratri':            'சரத் நவராத்திரி',
    'Golu':                       'கொலு',
    'Maha Navami':                'மஹா நவமி',
    'Vijayadashami':              'விஜயதசமி',
    'Mahalaya Amavasya':          'மகாளய அமாவாசை',
    'Jivitputrika Vrat (Jitiya)':          'ஜீவிதபுத்ரிகா விரதம்',
    'Sharad Purnima':             'சரத் பவுர்ணமி',
    'Karva Chauth':               'கர்வா சௌத்',
    'Ahoi Ashtami':               'அஹோய் அஷ்டமி',
    'Dhanteras':                  'தன்தேரஸ்',
    'Naraka Chaturdashi':         'நரக சதுர்தசி',
    'Diwali':                     'தீபாவளி',
    'Govardhan Puja':             'கோவர்தன் பூஜை',
    'Bhai Dooj':                  'பாய் தூஜ்',
    'Chhath — Nahay Khay':        'சட் — நஹாய் காய்',
    'Chhath — Kharna':            'சட் — கர்ணா',
    'Chhath — Sandhya Arghya':    'சட் — சாயங்கால அர்க்கியம்',
    'Chhath — Usha Arghya':       'சட் — உஷா அர்க்கியம்',
    'Devutthana Ekadashi':        'தேவுத்தான ஏகாதசி',
    'Tulsi Vivah':                'துளசி விவாஹம்',
    'Kartik Purnima':             'கார்த்திகை பவுர்ணமி',
    'Gita Jayanti':               'கீதா ஜயந்தி',
    'Vasant Panchami':            'வசந்த பஞ்சமி',
    'Maha Shivaratri':            'மஹா சிவராத்திரி',
    'Holika Dahan':               'ஹோலிகா தகனம்',
    'Ekadashi':                   'ஏகாதசி',
  };

  static const _bn = <String, String>{
    'Baisakhi / Vishu':                        'বৈশাখী / বিষু',
    'Makar Sankranti / Pongal':                'মকর সংক্রান্তি / পোঙ্গল',
    'Gudi Padwa / Ugadi / Chaitra Navratri':   'গুড়ি পড়বা / উগাদি / চৈত্র নবরাত্রি',
    'Maha Ashtami':               'মহা অষ্টমী',
    'Ram Navami':                 'রাম নবমী',
    'Hanuman Jayanti':            'হনুমান জয়ন্তী',
    'Holi':                       'হোলি',
    'Akshaya Tritiya':            'অক্ষয় তৃতীয়া',
    'Buddha Purnima':             'বুদ্ধ পূর্ণিমা',
    'Ganga Dussehra':             'গঙ্গা দশহরা',
    'Nirjala Ekadashi':           'নির্জলা একাদশী',
    'Vat Savitri':                'বট সাবিত্রী',
    'Hariyali Teej':              'হরিয়ালি তীজ',
    'Hartalika Teej':             'হরতালিকা তীজ',
    'Rath Yatra':                 'রথ যাত্রা',
    'Devshayani Ekadashi':        'দেবশয়নী একাদশী',
    'Guru Purnima':               'গুরু পূর্ণিমা',
    'Nag Panchami':               'নাগ পঞ্চমী',
    'Raksha Bandhan':             'রক্ষা বন্ধন',
    'Krishna Janmashtami':        'কৃষ্ণ জন্মাষ্টমী',
    'Ganesh Chaturthi':           'গণেশ চতুর্থী',
    'Anant Chaturdashi':          'অনন্ত চতুর্দশী',
    'Sharad Navratri':            'শারদ নবরাত্রি',
    'Golu':                       'গোলু',
    'Maha Navami':                'মহা নবমী',
    'Vijayadashami':              'বিজয়দশমী',
    'Mahalaya Amavasya':          'মহালয়া অমাবস্যা',
    'Jivitputrika Vrat (Jitiya)':          'জিতিয়া ব্রত',
    'Sharad Purnima':             'শরৎ পূর্ণিমা',
    'Karva Chauth':               'করবা চৌথ',
    'Ahoi Ashtami':               'অহোই অষ্টমী',
    'Dhanteras':                  'ধনতেরাস',
    'Naraka Chaturdashi':         'নরক চতুর্দশী',
    'Diwali':                     'দীপাবলি',
    'Govardhan Puja':             'গোবর্ধন পূজা',
    'Bhai Dooj':                  'ভাই দুজ',
    'Chhath — Nahay Khay':        'ছট — নহায় খায়',
    'Chhath — Kharna':            'ছট — খরনা',
    'Chhath — Sandhya Arghya':    'ছট — সন্ধ্যা অর্ঘ্য',
    'Chhath — Usha Arghya':       'ছট — ঊষা অর্ঘ্য',
    'Devutthana Ekadashi':        'দেবউত্থান একাদশী',
    'Tulsi Vivah':                'তুলসী বিবাহ',
    'Kartik Purnima':             'কার্তিক পূর্ণিমা',
    'Gita Jayanti':               'গীতা জয়ন্তী',
    'Vasant Panchami':            'বসন্ত পঞ্চমী',
    'Maha Shivaratri':            'মহাশিবরাত্রি',
    'Holika Dahan':               'হোলিকা দহন',
    'Ekadashi':                   'একাদশী',
  };

  static const _or = <String, String>{
    'Baisakhi / Vishu':                       'ବୈସାଖୀ / ବିଷୁ',
    'Makar Sankranti / Pongal':               'ମକର ସଂକ୍ରାନ୍ତି / ପୋଙ୍ଗଲ',
    'Gudi Padwa / Ugadi / Chaitra Navratri':  'ଗୁଡ଼ି ପଡ୍ୱା / ଉଗାଦି / ଚୈତ୍ର ନବରାତ୍ରୀ',
    'Maha Ashtami':               'ମହା ଅଷ୍ଟମୀ',
    'Ram Navami':                 'ରାମ ନବମୀ',
    'Hanuman Jayanti':            'ହନୁମାନ ଜୟନ୍ତୀ',
    'Holi':                       'ହୋଲି',
    'Akshaya Tritiya':            'ଅକ୍ଷୟ ତୃତୀୟା',
    'Buddha Purnima':             'ବୁଦ୍ଧ ପୂର୍ଣ୍ଣିମା',
    'Ganga Dussehra':             'ଗଙ୍ଗା ଦଶହରା',
    'Nirjala Ekadashi':           'ନିର୍ଜଳ ଏକାଦଶୀ',
    'Vat Savitri':                'ବଟ ସାବିତ୍ରୀ',
    'Hariyali Teej':              'ହରିୟାଳୀ ତୀଜ',
    'Hartalika Teej':             'ହରତାଳିକା ତୀଜ',
    'Rath Yatra':                 'ରଥ ଯାତ୍ରା',
    'Devshayani Ekadashi':        'ଦେବଶୟନୀ ଏକାଦଶୀ',
    'Guru Purnima':               'ଗୁରୁ ପୂର୍ଣ୍ଣିମା',
    'Nag Panchami':               'ନାଗ ପଞ୍ଚମୀ',
    'Raksha Bandhan':             'ରକ୍ଷା ବନ୍ଧନ',
    'Krishna Janmashtami':        'କୃଷ୍ଣ ଜନ୍ମାଷ୍ଟମୀ',
    'Ganesh Chaturthi':           'ଗଣେଶ ଚତୁର୍ଥୀ',
    'Anant Chaturdashi':          'ଅନନ୍ତ ଚତୁର୍ଦ୍ଦଶୀ',
    'Sharad Navratri':            'ଶାରଦ ନବରାତ୍ରୀ',
    'Golu':                       'ଗୋଲୁ',
    'Maha Navami':                'ମହା ନବମୀ',
    'Vijayadashami':              'ବିଜୟ ଦଶମୀ',
    'Mahalaya Amavasya':          'ମହାଳୟ ଅମାବାସ୍ୟା',
    'Jivitputrika Vrat (Jitiya)':         'ଜୀବିତପୁତ୍ରିକା ବ୍ରତ',
    'Sharad Purnima':             'ଶରତ ପୂର୍ଣ୍ଣିମା',
    'Karva Chauth':               'କରବା ଚୌଥ',
    'Ahoi Ashtami':               'ଅହୋଇ ଅଷ୍ଟମୀ',
    'Dhanteras':                  'ଧନ୍ତେରାସ',
    'Naraka Chaturdashi':         'ନରକ ଚତୁର୍ଦ୍ଦଶୀ',
    'Diwali':                     'ଦୀପାଳୀ',
    'Govardhan Puja':             'ଗୋବର୍ଦ୍ଧନ ପୂଜା',
    'Bhai Dooj':                  'ଭାଇ ଦ୍ୱିଜ',
    'Chhath — Nahay Khay':        'ଛଠ — ନହୟ ଖାୟ',
    'Chhath — Kharna':            'ଛଠ — ଖର୍ନା',
    'Chhath — Sandhya Arghya':    'ଛଠ — ସନ୍ଧ୍ୟା ଅର୍ଘ୍ୟ',
    'Chhath — Usha Arghya':       'ଛଠ — ଉଷା ଅର୍ଘ୍ୟ',
    'Devutthana Ekadashi':        'ଦେବଉଠାଣୀ ଏକାଦଶୀ',
    'Tulsi Vivah':                'ତୁଳସୀ ବିବାହ',
    'Kartik Purnima':             'କାର୍ତ୍ତିକ ପୂର୍ଣ୍ଣିମା',
    'Gita Jayanti':               'ଗୀତା ଜୟନ୍ତୀ',
    'Vasant Panchami':            'ବସନ୍ତ ପଞ୍ଚମୀ',
    'Maha Shivaratri':            'ମହାଶିବ ରାତ୍ରି',
    'Holika Dahan':               'ହୋଲିକା ଦହନ',
    'Ekadashi':                   'ଏକାଦଶୀ',
  };

  static const _te = <String, String>{
    'Baisakhi / Vishu':                       'బైసాఖి / విషు',
    'Makar Sankranti / Pongal':               'మకర సంక్రాంతి / పొంగల్',
    'Gudi Padwa / Ugadi / Chaitra Navratri':  'గుడి పడ్వా / ఉగాది / చైత్ర నవరాత్రి',
    'Maha Ashtami':               'మహా అష్టమి',
    'Ram Navami':                 'రామ నవమి',
    'Hanuman Jayanti':            'హనుమాన్ జయంతి',
    'Holi':                       'హోలీ',
    'Akshaya Tritiya':            'అక్షయ తృతీయ',
    'Buddha Purnima':             'బుద్ధ పూర్ణిమ',
    'Ganga Dussehra':             'గంగా దసహర',
    'Nirjala Ekadashi':           'నిర్జల ఏకాదశి',
    'Vat Savitri':                'వట సావిత్రి',
    'Hariyali Teej':              'హరియాళి తీజ్',
    'Hartalika Teej':             'హర్తాళిక తీజ్',
    'Rath Yatra':                 'రథ యాత్ర',
    'Devshayani Ekadashi':        'దేవశయని ఏకాదశి',
    'Guru Purnima':               'గురు పూర్ణిమ',
    'Nag Panchami':               'నాగ పంచమి',
    'Raksha Bandhan':             'రక్షా బంధన్',
    'Krishna Janmashtami':        'కృష్ణ జన్మాష్టమి',
    'Ganesh Chaturthi':           'గణేశ చతుర్థి',
    'Anant Chaturdashi':          'అనంత చతుర్దశి',
    'Sharad Navratri':            'శారద నవరాత్రి',
    'Golu':                       'గొలు',
    'Maha Navami':                'మహా నవమి',
    'Vijayadashami':              'విజయదశమి',
    'Mahalaya Amavasya':          'మహాలయ అమావాస్య',
    'Jivitputrika Vrat (Jitiya)':         'జీవిత్పుత్రికా వ్రతం',
    'Sharad Purnima':             'శరత్ పూర్ణిమ',
    'Karva Chauth':               'కర్వా చౌత్',
    'Ahoi Ashtami':               'అహోయ్ అష్టమి',
    'Dhanteras':                  'ధనత్రయోదశి',
    'Naraka Chaturdashi':         'నరక చతుర్దశి',
    'Diwali':                     'దీపావళి',
    'Govardhan Puja':             'గోవర్ధన పూజ',
    'Bhai Dooj':                  'భాయ్ దూజ్',
    'Chhath — Nahay Khay':        'ఛఠ్ — నహాయ్ ఖాయ్',
    'Chhath — Kharna':            'ఛఠ్ — ఖర్నా',
    'Chhath — Sandhya Arghya':    'ఛఠ్ — సంధ్యా అర్ఘ్యం',
    'Chhath — Usha Arghya':       'ఛఠ్ — ఉష అర్ఘ్యం',
    'Devutthana Ekadashi':        'దేవోత్థాన ఏకాదశి',
    'Tulsi Vivah':                'తులసి వివాహ',
    'Kartik Purnima':             'కార్తీక పూర్ణిమ',
    'Gita Jayanti':               'గీతా జయంతి',
    'Vasant Panchami':            'వసంత పంచమి',
    'Maha Shivaratri':            'మహా శివరాత్రి',
    'Holika Dahan':               'హోలికా దహన',
    'Ekadashi':                   'ఏకాదశి',
  };

  static const _ml = <String, String>{
    'Baisakhi / Vishu':                       'ബൈസാഖി / വിഷു',
    'Makar Sankranti / Pongal':               'മകര സംക്രാന്തി / പൊങ്കൽ',
    'Gudi Padwa / Ugadi / Chaitra Navratri':  'ഉഗാദി / ഗുഡി പഡ്വ / ചൈത്ര നവരാത്രി',
    'Maha Ashtami':               'മഹാ അഷ്ടമി',
    'Ram Navami':                 'രാമ നവമി',
    'Hanuman Jayanti':            'ഹനുമാൻ ജയന്തി',
    'Holi':                       'ഹോളി',
    'Akshaya Tritiya':            'അക്ഷയ തൃതീയ',
    'Buddha Purnima':             'ബുദ്ധ പൂർണ്ണിമ',
    'Ganga Dussehra':             'ഗംഗാ ദശഹര',
    'Nirjala Ekadashi':           'നിർജല ഏകാദശി',
    'Vat Savitri':                'വട സാവിത്രി',
    'Hariyali Teej':              'ഹരിയാലി തീജ്',
    'Hartalika Teej':             'ഹർതാലിക തീജ്',
    'Rath Yatra':                 'രഥ യാത്ര',
    'Devshayani Ekadashi':        'ദേവശയനി ഏകാദശി',
    'Guru Purnima':               'ഗുരു പൂർണ്ണിമ',
    'Nag Panchami':               'നാഗ പഞ്ചമി',
    'Raksha Bandhan':             'രക്ഷാ ബന്ധൻ',
    'Krishna Janmashtami':        'കൃഷ്ണ ജന്മാഷ്ടമി',
    'Ganesh Chaturthi':           'ഗണേശ ചതുർഥി',
    'Anant Chaturdashi':          'അനന്ത ചതുർദശി',
    'Sharad Navratri':            'ശാരദ നവരാത്രി',
    'Golu':                       'കൊലു',
    'Maha Navami':                'മഹാ നവമി',
    'Vijayadashami':              'വിജയദശമി',
    'Mahalaya Amavasya':          'മഹാലയ അമാവാസ്യ',
    'Jivitputrika Vrat (Jitiya)':         'ജീവിത്പുത്രിക വ്രതം',
    'Sharad Purnima':             'ശരത് പൂർണ്ണിമ',
    'Karva Chauth':               'കർവ ചൗത്',
    'Ahoi Ashtami':               'അഹോയ് അഷ്ടമി',
    'Dhanteras':                  'ധന്ത്രയോദശി',
    'Naraka Chaturdashi':         'നരക ചതുർദശി',
    'Diwali':                     'ദീപാവലി',
    'Govardhan Puja':             'ഗോവർദ്ധൻ പൂജ',
    'Bhai Dooj':                  'ഭായ് ദൂജ്',
    'Chhath — Nahay Khay':        'ഛഠ് — നഹായ് ഖായ്',
    'Chhath — Kharna':            'ഛഠ് — ഖർണ',
    'Chhath — Sandhya Arghya':    'ഛഠ് — സന്ധ്യ അർഘ്യം',
    'Chhath — Usha Arghya':       'ഛഠ് — ഉഷ അർഘ്യം',
    'Devutthana Ekadashi':        'ദേവോത്ഥാന ഏകാദശി',
    'Tulsi Vivah':                'തുളസി വിവാഹ',
    'Kartik Purnima':             'കാർത്തിക പൂർണ്ണിമ',
    'Gita Jayanti':               'ഗീതാ ജയന്തി',
    'Vasant Panchami':            'വസന്ത പഞ്ചമി',
    'Maha Shivaratri':            'മഹാ ശിവരാത്രി',
    'Holika Dahan':               'ഹോളിക ദഹനം',
    'Ekadashi':                   'ഏകാദശി',
  };

  static const _kn = <String, String>{
    'Baisakhi / Vishu':                       'ಬೈಸಾಖಿ / ವಿಷು',
    'Makar Sankranti / Pongal':               'ಮಕರ ಸಂಕ್ರಾಂತಿ / ಪೊಂಗಲ್',
    'Gudi Padwa / Ugadi / Chaitra Navratri':  'ಉಗಾದಿ / ಗುಡಿ ಪಾಡ್ವ / ಚೈತ್ರ ನವರಾತ್ರಿ',
    'Maha Ashtami':               'ಮಹಾ ಅಷ್ಟಮಿ',
    'Ram Navami':                 'ರಾಮ ನವಮಿ',
    'Hanuman Jayanti':            'ಹನುಮಾನ್ ಜಯಂತಿ',
    'Holi':                       'ಹೋಳಿ',
    'Akshaya Tritiya':            'ಅಕ್ಷಯ ತೃತೀಯ',
    'Buddha Purnima':             'ಬುದ್ಧ ಪೂರ್ಣಿಮ',
    'Ganga Dussehra':             'ಗಂಗಾ ದಶಹರ',
    'Nirjala Ekadashi':           'ನಿರ್ಜಲ ಏಕಾದಶಿ',
    'Vat Savitri':                'ವಟ ಸಾವಿತ್ರಿ',
    'Hariyali Teej':              'ಹರಿಯಾಳಿ ತೀಜ್',
    'Hartalika Teej':             'ಹರ್ತಾಳಿಕ ತೀಜ್',
    'Rath Yatra':                 'ರಥ ಯಾತ್ರೆ',
    'Devshayani Ekadashi':        'ದೇವಶಯನಿ ಏಕಾದಶಿ',
    'Guru Purnima':               'ಗುರು ಪೂರ್ಣಿಮ',
    'Nag Panchami':               'ನಾಗ ಪಂಚಮಿ',
    'Raksha Bandhan':             'ರಕ್ಷಾ ಬಂಧನ',
    'Krishna Janmashtami':        'ಕೃಷ್ಣ ಜನ್ಮಾಷ್ಟಮಿ',
    'Ganesh Chaturthi':           'ಗಣೇಶ ಚತುರ್ಥಿ',
    'Anant Chaturdashi':          'ಅನಂತ ಚತುರ್ದಶಿ',
    'Sharad Navratri':            'ಶಾರದ ನವರಾತ್ರಿ',
    'Golu':                       'ಗೊಲ್ಲು',
    'Maha Navami':                'ಮಹಾ ನವಮಿ',
    'Vijayadashami':              'ವಿಜಯದಶಮಿ',
    'Mahalaya Amavasya':          'ಮಹಾಲಯ ಅಮಾವಾಸ್ಯೆ',
    'Jivitputrika Vrat (Jitiya)':         'ಜೀವಿತ್ಪುತ್ರಿಕಾ ವ್ರತ',
    'Sharad Purnima':             'ಶರತ್ ಪೂರ್ಣಿಮ',
    'Karva Chauth':               'ಕರ್ವಾ ಚೌತ್',
    'Ahoi Ashtami':               'ಅಹೋಯ್ ಅಷ್ಟಮಿ',
    'Dhanteras':                  'ಧನ್ತ್ರಯೋದಶಿ',
    'Naraka Chaturdashi':         'ನರಕ ಚತುರ್ದಶಿ',
    'Diwali':                     'ದೀಪಾವಳಿ',
    'Govardhan Puja':             'ಗೋವರ್ಧನ ಪೂಜೆ',
    'Bhai Dooj':                  'ಭಾಯಿ ದೂಜ್',
    'Chhath — Nahay Khay':        'ಛಠ್ — ನಹಾಯ್ ಖಾಯ್',
    'Chhath — Kharna':            'ಛಠ್ — ಖರ್ನ',
    'Chhath — Sandhya Arghya':    'ಛಠ್ — ಸಂಧ್ಯಾ ಅರ್ಘ್ಯ',
    'Chhath — Usha Arghya':       'ಛಠ್ — ಉಷಾ ಅರ್ಘ್ಯ',
    'Devutthana Ekadashi':        'ದೇವೋತ್ಥಾನ ಏಕಾದಶಿ',
    'Tulsi Vivah':                'ತುಳಸಿ ವಿವಾಹ',
    'Kartik Purnima':             'ಕಾರ್ತೀಕ ಪೂರ್ಣಿಮ',
    'Gita Jayanti':               'ಗೀತಾ ಜಯಂತಿ',
    'Vasant Panchami':            'ವಸಂತ ಪಂಚಮಿ',
    'Maha Shivaratri':            'ಮಹಾ ಶಿವರಾತ್ರಿ',
    'Holika Dahan':               'ಹೋಳಿಕ ದಹನ',
    'Ekadashi':                   'ಏಕಾದಶಿ',
  };
}
